version: '3.8'

services:
  app:
    build: Dockerfile.dev
    ports:
      - "${PORT}:3000"
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PWD}@${PG_HOST}:${PG_PORT}/${PG_DB}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}

      PG_USER: ${PG_USER}
      PG_DB: ${PG_DB}
      PG_PWD: ${PG_PWD}
      PG_HOST: db
      PG_PORT: ${PG_PORT}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: ${PG_DB}